services:
  sldl:
    build:
      context: .
    environment:
      - TZ=Australia/Sydney
      - PUID=1028
      - PGID=65536
    volumes:
      - volume1/docker/sldl:/config
      - volume1/Data:/data
